version: '3.6'
services:
  apache:
    image: php:7.3-apache
    build: .
    ports:
      - "80:80" # web
      - "443:443" # web secure
      - "9001:9000" # xdebug
      # - "35729:35729" # live reload
    volumes:
      - _build-sync:/var/www/html:nocopy
      - ./.docker/apache:/etc/apache2/sites-enabled
      - ~/.composer:/var/www/.composer
      - ~/.npm:/var/www/.npm
      - ~/.docker:/var/www/.docker
      # - ~/.nvm:/var/www/.nvm
    environment:
      XDEBUG_CONFIG: "remote_host=10.254.254.254 remote_connect_back=0"
      PHP_IDE_CONFIG: "serverName=Docker"
    networks:
      - pr_main-network

networks:
  pr_main-network:
    external: true

volumes:
  _build-sync:
    external: true