#!/usr/bin/env bash
docker-sync start && \
docker-compose up -d && \
echo "
===================== 🚀 Done 🚀 ===================

      Created by Muhammad Mian
      Access your new links:

      Web server: http://localhost/
      PHPMyAdmin: http://localhost:8080
      Local emails: http://localhost:8025
      Elasticsearch: http://localhost:9200

===================== 🚀 Done 🚀 ==================="
