#!/usr/bin/env bash

if [[ -f "docker-sync.yml" ]]
then
  # START PHP 7.3 Xdebug Config #
  VERSION=$(grep -c "7.3-apache" docker-compose.yml)
  if [[ $VERSION -eq "1" ]]; then
    echo "Configuring Xdebug for php7.3"
    sudo ifconfig lo0 alias 10.254.254.254
  fi
  # END PHP 7.3 Xdebug Config ###

  docker-sync start
fi

docker-compose up -d

echo "
===================== 🚀 Done 🚀 ===================

      Created by Muhammad Mian
      Access your new links:

      🌎 Web server: http://localhost/

===================== 🚀 Done 🚀 ==================="
